name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      compose-file:
        description: 'Path to Docker Compose file'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            run:
              echo "Checkout code"

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name
          run:
            echo "Login to Heroku"

      - name: Deploy Docker Compose to Heroku
        run: |
          docker-compose -f ${{ github.event.inputs.compose-file }} build
          docker-compose -f ${{ github.event.inputs.compose-file }} push
          echo "Deploy Docker Compose to Heroku"
