name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      compose-file:
        description: 'Path to Docker Compose file'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku
        uses: actions/heroku@v1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy Docker Compose to Heroku
        run: |
          heroku container:login
          docker-compose -f ${{ github.event.inputs.compose-file }} build
          heroku container:push web
          heroku container:release web
